# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target '00_Sign In' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 00_Sign In
pod 'GoogleSignIn'
pod 'KakaoSDK' 

end
